"""create tables

Revision ID: bd3044ce1a00
Revises: 4ae348910537
Create Date: 2024-09-17 22:33:23.196562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3044ce1a00'
down_revision = '4ae348910537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('fk_concerts_band_id_bands')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_concerts_venue_id_venues')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concerts_table',
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('fk_concerts_table_band_id_bands')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_concerts_table_venue_id_venues')),
    sa.PrimaryKeyConstraint('band_id', 'venue_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerts_table')
    op.drop_table('concerts')
    op.drop_table('venues')
    op.drop_table('bands')
    # ### end Alembic commands ###
