"""revises tables

Revision ID: cf84b7e6fd9b
Revises: bd3044ce1a00
Create Date: 2024-09-17 23:04:17.570601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf84b7e6fd9b'
down_revision = 'bd3044ce1a00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerts_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts_table',
    sa.Column('band_id', sa.INTEGER(), nullable=False),
    sa.Column('venue_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name='fk_concerts_table_band_id_bands'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='fk_concerts_table_venue_id_venues'),
    sa.PrimaryKeyConstraint('band_id', 'venue_id')
    )
    # ### end Alembic commands ###
